sonar.projectKey=misiuleczek02_zadanie7-client
sonar.organization=misiuleczek022
sonar.projectName=Zadanie 7 Client
sonar.projectVersion=1.0

sonar.sources=src
sonar.exclusions=src/**/*.test.js,src/**/*.test.jsx,src/setupTests.js,build/**,coverage/**

sonar.tests=src
sonar.test.inclusions=src/**/*.test.js,src/**/*.test.jsx

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
